### ISSUE TITLE
Error running eval_linear_satellite.py with current version of src code

### ISSUE THREAD

**Issue by agarciaburgos** [MIT-REALM/neural_clbf#15]
I ran the train_linear_satellite.py but it is only training until epoch 100. It fails to continue after this epoch. 

I then tried to run the evaluation script associated with linear_satellite.py (i.e., eval_linear_satellite.py) but I get the following error. I disabled_gurobi=True to False but that didn't help with the issue. The error I get during the evaluation script is the one below

File "/home/kiko/anaconda3/envs/neural_clbf/lib/python3.9/site-packages/cvxpy/utilities/canonical.py", line 113, in _deepcopy_
    raise NotImplementedError('Creating a deepcopy of a CVXPY expression is not supported. '
NotImplementedError: Creating a deepcopy of a CVXPY expression is not supported. Use .copy() instead.

Can someone check the current version of the code and help me fix the bug in the src code?

**Comment by dawsonc** [comment]
I've been able to reproduce this bug and there should be a PR coming shortly that resolves it. Thanks for reporting the issue here!

**Comment by dawsonc** [comment]
This should be resolved as of PR #16, but please re-open if the issue persists and I'll be happy to help.
