### ISSUE TITLE
Missing file eval_single_track_car.py

### ISSUE THREAD

**Issue by KehanLong** [MIT-REALM/neural_clbf#5]
Hi, 

I am trying to reproduce the results in the paper "Safe Control with Learned Certificates: A Survey of Neural Lyapunov, Barrier, and Contraction methods", specifically the example of CLF for car tracking. However, it seems that the file evaluation/eval_single_track_car.py is missing in the repo. 

Could you please help with it? Thanks in advance.

**Comment by dawsonc** [comment]
Hi! Happy to help as you work through our experiments, and sorry it took so long for me to respond!

Perhaps your version of the code is out of date? I'm seeing that file [here](https://github.com/MIT-REALM/neural_clbf/blob/main/neural_clbf/evaluation/eval_single_track_car.py). Does that fix your issue?

**Comment by KehanLong** [comment]
Thanks for your help! The current version works fine.
