### ISSUE TITLE
ImportError due to torchmetrics version

### ISSUE THREAD

**Issue by rallen10** [MIT-REALM/neural_clbf#7]
When installing and running `pytest`, all tests fail with the error

```
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data'
```

See related problem [here](https://github.com/cv-rits/MonoScene/issues/18) with [proposed solution](https://github.com/NVIDIA/DeepLearningExamples/issues/1113#issuecomment-1102969461) to simply downgrade `torchmetrics` to `v0.6.0`

I recommend pinning `torchmetrics ==0.6.0` in requirements so new users don't run into this problem; at least until a more robust and less rigid solution is implemented.

In the mean time new users can resolve by manually installing torchmetrics with

```
conda activate neural_clbf
pip install torchmetrics==0.6.0
```

**Comment by djaustin1** [comment]
Have this exact issue, however, I get the following error when I try to run conda activate neural_clbf.  What am I missing?  Thanks.

EnvironmentNameNotFound: Could not find conda environment: neural_clbf
You can list all discoverable environments with `conda info --envs`.

![image](https://user-images.githubusercontent.com/119802891/205542921-81356af5-c9e2-4e6d-8e2b-60792d6d24b2.png)

**Comment by dawsonc** [comment]
@rallen10 Thanks for raising this issue, and sorry for the delayed response. I think `torchmetrics` is pinned at `0.5.1` now (I think I made this change sometime in the last month or so, before I realized people were actually using my code :sweat_smile: )

**Comment by dawsonc** [comment]
@djaustin1 I think your issue is that you do not seem to have created a conda environment for `neural_clbf`. There are instructions in the README:
```
conda create --name neural_clbf python=3.9
conda activate neural_clbf
pip install -e .
pip install -r requirements.txt
```

Does that work for you?
