### ISSUE TITLE
Make Gurobi an optional flag. 

### ISSUE THREAD

**Issue by rallen10** [MIT-REALM/neural_clbf#8]
I am trying to  get up and running with this codebase and I immediately run into a licensing problem when I try to run:

```
python neural_clbf/training/train_inverted_pendulum.py
.
.
.
  File "src/gurobipy/env.pxi", line 67, in gurobipy.Env.__init__
  File "src/gurobipy/gurobi.pxi", line 32, in gurobipy.gurobi._getdefaultenv
  File "src/gurobipy/env.pxi", line 67, in gurobipy.Env.__init__
gurobipy.GurobiError: License expired 2022-01-13
```

Since CVX is already a dependency, it seems that you could just set an optional flag in [clf_controller.py](https://github.com/MIT-REALM/neural_clbf/blob/7390ab264c79d2f8a01782ea94353352d2d7930e/neural_clbf/controllers/clf_controller.py#L399)  to use gurobi if desired

Gurobi's academic licensing has several hoops to jump through in order to obtain. Not only does it require an academic affiliation (e.g. email), you actually have to be connected to a [university-affiliated IP](https://support.gurobi.com/hc/en-us/articles/360038994471) for the license install to work.

**Comment by rallen10** [comment]
Proposed fix here: https://github.com/MIT-REALM/neural_clbf/pull/9

**Comment by dawsonc** [comment]
Thanks for starting a PR on this; we can move discussion over to #9
